# Generated by Django 4.0.6 on 2022-08-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_alter_employees_cellphone_alter_management_cellphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=8, verbose_name='Номер телефона'),
        ),
    ]
