# Generated by Django 4.0.6 on 2022-08-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_alter_employees_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=8, null=True, verbose_name='Номер телефона'),
        ),
    ]
