# Generated by Django 4.0.6 on 2022-08-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0010_alter_management_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
