# Generated by Django 4.0.6 on 2022-08-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0014_alter_employees_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='phonebook.department', verbose_name='Департамент'),
        ),
    ]
