# Generated by Django 4.0.6 on 2022-08-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0015_employees_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='phonebook.department', verbose_name='Департамент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='phonebook.division', verbose_name='Отдел'),
        ),
    ]
