# Generated by Django 4.0.6 on 2022-08-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0016_alter_employees_department_alter_employees_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['phone'], 'verbose_name': 'Номер телефона!', 'verbose_name_plural': 'Номера телефонов'},
        ),
    ]
