# Generated by Django 4.0.6 on 2022-08-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0017_alter_phone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['phone'], 'verbose_name': 'Номер телефона', 'verbose_name_plural': 'Номера телефонов'},
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
